### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by mictadlo** [nibtehaz/NORTH-app#2]
Hi,
I uploaded to NORTH-app a fasta file but I did not have any outliners.fasta file. When I clicked on start training  to the next step 

![Screen Shot 2019-04-18 at 9 02 11 am](https://user-images.githubusercontent.com/588297/56326523-b1b84b80-61b9-11e9-8358-f59a1acdbe9f.png)
![Screen Shot 2019-04-18 at 9 02 45 am](https://user-images.githubusercontent.com/588297/56326524-b1b84b80-61b9-11e9-85f9-31205b92a271.png)

I got the below errors:

```
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/geneious/projects/NORTH-app/tempdata/phase1_4.json' }
{ Error: ENOENT: no such file or directory, open '/home/geneious/projects/NORTH-app/tempdata/phase1_4.json'
    at Object.openSync (fs.js:436:3)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:160:31)
    at Object.readFileSync (fs.js:341:35)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:580:40)
    at app.get (/home/geneious/projects/NORTH-app/express_app.js:33:27)
    at Layer.handle [as handle_request] (/home/geneious/projects/NORTH-app/node_modules/.registry.npmjs.org/express/4.16.4/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/geneious/projects/NORTH-app/node_modules/.registry.npmjs.org/express/4.16.4/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/geneious/projects/NORTH-app/node_modules/.registry.npmjs.org/express/4.16.4/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/geneious/projects/NORTH-app/node_modules/.registry.npmjs.org/express/4.16.4/node_modules/express/lib/router/layer.js:95:5)
    at /home/geneious/projects/NORTH-app/node_modules/.registry.npmjs.org/express/4.16.4/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/geneious/projects/NORTH-app/node_modules/.registry.npmjs.org/express/4.16.4/node_modules/express/lib/router/index.js:335:12)
    at next (/home/geneious/projects/NORTH-app/node_modules/.registry.npmjs.org/express/4.16.4/node_modules/express/lib/router/index.js:275:10)
    at next (/home/geneious/projects/NORTH-app/node_modules/.registry.npmjs.org/express/4.16.4/node_modules/express/lib/router/route.js:127:14)
    at next (/home/geneious/projects/NORTH-app/node_modules/.registry.npmjs.org/express/4.16.4/node_modules/express/lib/router/route.js:131:14)
    at next (/home/geneious/projects/NORTH-app/node_modules/.registry.npmjs.org/express/4.16.4/node_modules/express/lib/router/route.js:131:14)
    at next (/home/geneious/projects/NORTH-app/node_modules/.registry.npmjs.org/express/4.16.4/node_modules/express/lib/router/route.js:131:14)
    at next (/home/geneious/projects/NORTH-app/node_modules/.registry.npmjs.org/express/4.16.4/node_modules/express/lib/router/route.js:131:14)
    at next (/home/geneious/projects/NORTH-app/node_modules/.registry.npmjs.org/express/4.16.4/node_modules/express/lib/router/route.js:131:14)
    at next (/home/geneious/projects/NORTH-app/node_modules/.registry.npmjs.org/express/4.16.4/node_modules/express/lib/router/route.js:131:14)
    at next (/home/geneious/projects/NORTH-app/node_modules/.registry.npmjs.org/express/4.16.4/node_modules/express/lib/router/route.js:131:14)
    at next (/home/geneious/projects/NORTH-app/node_modules/.registry.npmjs.org/express/4.16.4/node_modules/express/lib/router/route.js:131:14)
    at next (/home/geneious/projects/NORTH-app/node_modules/.registry.npmjs.org/express/4.16.4/node_modules/express/lib/router/route.js:131:14)
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/geneious/projects/NORTH-app/tempdata/phase1_4.json' }
```

What did I miss?

Thank you in advance.

Michal

**Comment by nibtehaz** [comment]
Hello Michal,

Actually you didn't miss anything. The errors you are reporting don't mean anything. They were there for controlling the progress bar. If the file is found the progress bar would proceed, otherwise not. Initially Socket Io was used to control the progress bars, but it was too demanding for the cpu, so we planned this workaround.

But, I must ask. Why are you training with only one cluster? Is it because you're interested to find the outlier genes only ? If it's so you would need to provide some outlier genes to train the anomaly detection module.

Also, how is the fasta file formatted? I see only one cluster but the progress bar shows 9 clusters. It's a bit strange. Please have a look at the sample_data we've provided. These fasta files are generated and downloaded from UniProt. You don't need to download the fasta files from uniprot, but please make sure that the protein sequences in the fasta file follows the same format.

Thanks your interest in our NORTH project. Have a nice day :) 
Nabil

**Comment by mictadlo** [comment]
Hi Nabil,
I changed the input file to this (ftp://ftp.solgenomics.net/genomes/Solanum_lycopersicum/annotation/ITAG3.2_release/ITAG3.2_proteins.fasta). Now I have `Reading Clusters 0/1` for around a day.

Should I use another protein FASTA file from another species? I'm new to this type of analyze. 

Thank you in advance,

Michal
