### ISSUE TITLE
Error at npm start

### ISSUE THREAD

**Issue by igigkuo** [nibtehaz/NORTH-app#3]
Hi,

I was trying to install NORTH on linux. An error occurred when I run "npm start" with reporting "Failed at the NORTH@1.0.0 start script 'electron .'" The npm-debug.log shows:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.10
3 info using node@v6.17.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle NORTH@1.0.0~prestart: NORTH@1.0.0
6 silly lifecycle NORTH@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle NORTH@1.0.0~start: NORTH@1.0.0
8 verbose lifecycle NORTH@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle NORTH@1.0.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/kuokuo/softwares/NORTH-app/node_modules/.bin:/home/kuokuo/anaconda3/bin:/home/kuokuo/anaconda3/condabin:/usr/local/rvm/gems/ruby-2.3.3/bin:/usr/local/rvm/gems/ruby-2.3.3@global/bin:/usr/local/rvm/rubies/ruby-2.3.3/bin:/usr/local/share/applications/R-3.4.3/bin:/home/kuokuo/perl5/bin:/usr/local/share/applications/exfat/fuse/bin:/usr/local/share/applications/exfat/fuse/bin:/usr/local/share/applications/exfat/fuse/bin:/usr/java/jdk1.8.0_151/bin:/usr/local/diamond-master:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/local/rvm/bin:/home/kuokuo/.local/bin:/home/kuokuo/bin:/home/kuokuo/softwares:/home/kuokuo/softwares/ncbi-blast-2.10.0+/bin:/home/kuokuo/softwares/ParaAT2.0:/home/kuokuo/softwares/KaKs_Calculator2.0/src:/home/kuokuo/softwares/MCScanX/downstream_analyses:/home/kuokuo/softwares/MCScanX:/home/kuokuo/softwares/tanghaibao-mcscan-4cfe0f5:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/home/kuokuo/anaconda3/bin:/home/kuokuo/softwares/cafehahnlab-code2/cafe
10 verbose lifecycle NORTH@1.0.0~start: CWD: /home/kuokuo/softwares/NORTH-app
11 silly lifecycle NORTH@1.0.0~start: Args: [ '-c', 'electron .' ]
12 info lifecycle NORTH@1.0.0~start: Failed to exec start script
13 verbose stack Error: NORTH@1.0.0 start: `electron .`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:33:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:920:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
14 verbose pkgid NORTH@1.0.0
15 verbose cwd /home/kuokuo/softwares/NORTH-app
16 error Linux 3.10.0-693.11.6.el7.x86_64
17 error argv "/usr/bin/node" "/usr/bin/npm" "start"
18 error node v6.17.1
19 error npm  v3.10.10
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error NORTH@1.0.0 start: `electron .`
24 error spawn ENOENT
25 error Failed at the NORTH@1.0.0 start script 'electron .'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the NORTH package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     electron .
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs NORTH
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls NORTH
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]
```

My system is CentOS Linux release 7.4.1708. May I ask what is the possible problem? Many thanks in advance!

**Comment by nibtehaz** [comment]
Hello,

Thank you for your interest in our project. Sorry to hear that you are facing such issues. Thank you again for providing such a detailed error log.

From the log what it appears to me first is that the version of node and npm. Would you please try updating them?

In my system I've the following versions

node v11.8.0
npm v6.5.0

Hope this helps. Thank you

**Comment by igigkuo** [comment]
Hi,

I have updated my system and the error disappeared. Thanks lot for your help!
